
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation col-1150" id="menuHangtag" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php /* @escapeNotVerified */ echo $_menu; ?>  
        <li class="level0 nav- last level-top ui-menu-item" role="presentation">
        	<a href="/hangtag/contact" class="level-top ui-corner-all ui-state-focus" tabindex="-1" role="menuitem"><span>Contact Us</span>
        	</a>
    	</li>     
    </ul>
</nav>
